### ISSUE TITLE
3.0.0.4.382.51640 rebase?

### ISSUE THREAD

**Issue by Eldenroot** [gzenux/asuswrt-rtn18u#10]
Are you planning to add fixes from 3.0.0.4.382.51640 (official latest Asus fw for RT-N18U)?

**Comment by gzenux** [comment]
Yes, this is already done. I am preparing upload to github. You can update it for a later.

**Comment by gzenux** [comment]
384.12-beta1 is available now, you can download it from website or check update by router.

**Comment by Eldenroot** [comment]
Thank you!
