### ISSUE TITLE
ping target site show in blank

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#12]
in the system manager, and open [web monitor], check ping,it have two site not show up.
![SLboat-Mac-Screen2019-10-1320 12 51](https://user-images.githubusercontent.com/4231376/66715434-ec601100-edf5-11e9-98a8-c6cbd7758f72.jpg)

**Comment by gzenux** [comment]
Which browser do you use? I think this issue might be the same with this [post](https://www.snbforums.com/threads/release-asuswrt-merlin-384-13-is-now-available.57860/#post-507454).

**Comment by SLboat** [comment]
Hi,im use chrome 


From SLboat

**Comment by SLboat** [comment]
> Which browser do you use? I think this issue might be the same with this [post](https://www.snbforums.com/threads/release-asuswrt-merlin-384-13-is-now-available.57860/#post-507454).

as i see, it not a mod bug, it's a merlin bug, so ,i will close this issue, thank you:)

and as i test chrome and safari, it's just same behave.
![SLboat-Mac-Screen2019-10-158 23 19](https://user-images.githubusercontent.com/4231376/66791176-ac984700-ef25-11e9-802a-7b6ce2fc4855.jpg)
![SLboat-Mac-Screen2019-10-158 24 20](https://user-images.githubusercontent.com/4231376/66791178-ac984700-ef25-11e9-998e-6a0344f96d1d.jpg)

**Comment by SLboat** [comment]
经过再度测试,无论中文和是英文语言都不能渲染出来,很奇怪,也许是因为它太长了,做了某种智能处理吧.你提供的网站里面的那人的情况确实是一样,里面得到的建议是换浏览器,我再手机,笔记本,电脑都试了都只能得到一样的结果.也许可能是因为utf8或者缓存的原因吧.

总而言之,这不是一个特别大的问题,非常感谢你的耐心回答.

**Comment by gzenux** [comment]
這已經不是瀏覽器的問題了，昨天追查了一下，發現是華碩的 prebuilt tool 無法處理那兩個文字（位置在 release/src/router/tools/Lnx_ToolHelp/LnxRmvTabs），後來退回華碩官方版本 3.0.0.4.382.51640一樣有這個問題，所以華碩的 prebuilt tool 沒有更新的情況下頂多只能進行 workaround 的後處理或者直接改變梅林原始的寫法，但兩者自然會有各自的缺點，因此我也不太打算修正這個問題。

**Comment by SLboat** [comment]
明白了!非常感谢!我觉得这个的最快解决应该是换个名字,让华硕去修理吧.

From SLboat
