### ISSUE TITLE
有任何计划合并梅林最新的384.13吗?

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#13]
看来我们似乎只落后这一个小小的版本了,不知道我们这个改动大不大,应该主要是gpio的适配等吧?关掉5G?希望能帮上忙,一起慢慢完善这个rtn18u的mod固件.

**Comment by SLboat** [comment]
一个无关紧要的小问题,在你们繁体字使用者看来,看懂简体字会费力吗?

**Comment by gzenux** [comment]
看得懂簡體字，只是會需要點時間適應不同辭彙的說法，大致上應該不會有溝通問題。

至於merlin官方版本384.13的問題，之前有一篇issue有解釋版本差異（詳見#6），摘要如下：
目前rtn18u版本384.12這版，實際上已經是合併merlin官方的384.13了（確切的說是tag: 384.13-mainline），從此專案repository中的tag: rtn18u_384.12可以看出來。

之間會有版本差異源自於 384.9 時由於缺乏華碩官方的 prebuilt binary blobs的更新導致無法如期release，結果是rtn18u 384.9釋出的時候，merlin 已經釋出384.10了，因此就錯開了。

近期merlin官方也持續進入384.14的開發，在這版當中，在mainline branch中引入了新的codebase(GPL 384_81116)，隨著merlin持續進版（引進新的codebase），無法跟上mainline是遲早的事情，因此目前在評估之後的版本（rtn18u後續384.13開發）是否要繼續合併mainline branch。

最後，這個專案使用的codebase是華碩官方 RT-N18U GPL release，不是從merlin官方移植而來，所以方向是相反的（移植merlin的code），你想幫忙這個專案的發展當然是歡迎的，只是從前面的狀況解說來看，此專案未來很可能會減緩開發步調跟同步引進merlin最新的版本，朝向只合併merlin的opensource更新發展。

**Comment by SLboat** [comment]
感谢耐心的解释.我有一个奇怪的想法,AC68U和18U的差别真的那么大吗?


From SLboat

**Comment by SLboat** [comment]
> 看得懂簡體字，只是會需要點時間適應不同辭彙的說法，大致上應該不會有溝通問題。
> 
> 至於merlin官方版本384.13的問題，之前有一篇issue有解釋版本差異（詳見#6），摘要如下：
> 目前rtn18u版本384.12這版，實際上已經是合併merlin官方的384.13了（確切的說是tag: 384.13-mainline），從此專案repository中的tag: rtn18u_384.12可以看出來。
> 
> 之間會有版本差異源自於 384.9 時由於缺乏華碩官方的 prebuilt binary blobs的更新導致無法如期release，結果是rtn18u 384.9釋出的時候，merlin 已經釋出384.10了，因此就錯開了。
> 
> 近期merlin官方也持續進入384.14的開發，在這版當中，在mainline branch中引入了新的codebase(GPL 384_81116)，隨著merlin持續進版（引進新的codebase），無法跟上mainline是遲早的事情，因此目前在評估之後的版本（rtn18u後續384.13開發）是否要繼續合併mainline branch。
> 
> 最後，這個專案使用的codebase是華碩官方 RT-N18U GPL release，不是從merlin官方移植而來，所以方向是相反的（移植merlin的code），你想幫忙這個專案的發展當然是歡迎的，只是從前面的狀況解說來看，此專案未來很可能會減緩開發步調跟同步引進merlin最新的版本，朝向只合併merlin的opensource更新發展。

抱歉,刚才在路上,没有仔细说完我的意思.
1. 关于384.13的,我也注意到commit里的区别里,很好奇,但是你一说我更加理解了.
2. 你所做的事情非常好,但是也非常复杂,我认为,因为你再试图让梅林相比原始固件的差别,得到diff,再返回到n18u身上,这里有几个来回的渠道问题,而梅林是一群人在维护,在这里你是单枪匹马.
3. 这个我真正想思考的问题,是我一直以来的疑惑...最初我买n18是的时候,就有很多人说它是ac68u的阉割版,去掉了5g芯片,双核变成了单核.实际上,我不知道你有没有试过,n18u可以直接刷官方的ac68u(恢复模式),也可以刷梅林的改版ac68u,它们似乎真的很接近,我想你肯定试过.只是有一些奇怪的问题: 指示灯错乱(usb2变成了power),reset 功能失灵,管理员账号密码失灵.

大陆的改版固件很多都是改改gpio,做下适配,你做的这个非常彻底,也非常完美主义,这让我疑惑,能不能抛开rt18u,找出它和ac68u的本质,做一些基本的修剪,去掉5g,gpio适配.这样就能更轻松的长期追随merlin呢?

**Comment by SLboat** [comment]
rt18u的某种精简版梅林 = ac68u梅林 - 5g功能 x gpio适配

这种可能性是不是很小呢?我看到新的梅林有个ai mesh功能,这个是很吃cpu还是必须靠5g来实现,会有很多内部的特别冲突吗?

所以回到所有事情的开头,梅林为什么一直都不肯支持rt-18u呢,也许是因为它们差别就真的那么大吗?又会回到一个问题,华硕的策略里就是让18u变成一个廉价版的68u,在大陆的二手市场(68u的售价高达400,而18u则100多,是人民币汇率),这是巨大的4倍差距,但我个人更喜欢18u,还是因为只拿它做交换机,我用别的做ap,而它的发热量更低.

非常感谢你做了这么一件事:)它很美好,可以web直刷,几乎完全兼容.也可以想象其中的工作并不轻松,而且未来我们将落后的这个糟糕消息,真希望是有一些简单的方法,让我们得到ac68u内核的2.4g+多功能支持.

**Comment by SLboat** [comment]
再问个额外的问题,我想在阁下改版的这个merlin装entware的话,我直接照着mwrlin的方式去做就可以了吗?我有点费解,我们这个改版固件是更贴近asus还是merlin,我也注意到merlin固件有个比如tools菜单,而我们这里是贴心的集成到系统设置里去了.

**Comment by SLboat** [comment]
> 再问个额外的问题,我想在阁下改版的这个merlin装entware的话,我直接照着mwrlin的方式去做就可以了吗?我有点费解,我们这个改版固件是更贴近asus还是merlin,我也注意到merlin固件有个比如tools菜单,而我们这里是贴心的集成到系统设置里去了.

这个从官方wiki找到了,安装到u盘,不用回答了,谢谢.

**Comment by gzenux** [comment]
謝謝你的想法分享，覺得你所提的想法應該也是可行的，只是這樣一來就是把 model 變更成 ac68u，如此的確可以承襲 ac68u 的 binary 更新。

所有事物都有優缺點的，就看從什麼角度切入。我使用 n18u 是希望它可以穩定、高效率的運行，而 merlin 的理念正好也是以華碩官方釋出的 GPL source 為基礎進行功能強化、以及修正錯誤。
只是後來才知道 merlin 宣稱某些因素不打算支援 n18u，因此才想說試著讓 n18u 支援 merlin 看看，所以自然而然會以 n18u 的 GPL 為基礎進行功能添加。

雖然華碩的 codebase 不斷進版，但從這陣子的專案維護所得到的經驗是：
1. 華碩進版所新增的功能大多都是私有的應用(AiMesh、AiProtection、AiCloud...等)，大多不會公開原始碼而且有些會跟 model 相依。
2. 發現華碩後來的 codebase 進版其實也是多著重在 11ac/11ax，幾乎沒有 11n 的功能新增（也就是不少 n18u 其實都用不到），在這樣的 codebase 下反而多少會增加 code size。
3. Merlin 所維護的專案排除進版華碩的 codebase 情況下，也多只能從 opensource、或自行實作功能；並且多少也會遇到 binary 不相容的問題。

以這個專案而言，基本上保留 n18u 華碩官方原廠軔體既有的功能下，又能整合 merlin 的 opensource 的強化與 bugfix，我個人認為其實已經達到當初創立這個專案的目標了。

對 merlin 專案來說，由於他們會持續進版 codebase，所以陸續會有跟不上更新的裝置會被停止支援（如 RT-AC56U），就算 ac68u 也會有被 merlin 停止支援的一天（只要華碩停止頻繁更新 binary）。
因為 binary 是個黑合子，我很難去確定華碩在程式的寫法完美相容所有狀況，因此就以確定可完整支援 n18u 的 GPL 為基礎來疊加 merlin 了。

不過你所提的方式我覺得是可行的，有興趣的話其實你也可以另創專案去實踐你的想法，我這邊則可以提供之前整合這個專案的一些相關經驗，大家可以互相討論這樣~

**Comment by SLboat** [comment]
> 謝謝你的想法分享，覺得你所提的想法應該也是可行的，只是這樣一來就是把 model 變更成 ac68u，如此的確可以承襲 ac68u 的 binary 更新。
> 
> 所有事物都有優缺點的，就看從什麼角度切入。我使用 n18u 是希望它可以穩定、高效率的運行，而 merlin 的理念正好也是以華碩官方釋出的 GPL source 為基礎進行功能強化、以及修正錯誤。
> 只是後來才知道 merlin 宣稱某些因素不打算支援 n18u，因此才想說試著讓 n18u 支援 merlin 看看，所以自然而然會以 n18u 的 GPL 為基礎進行功能添加。
> 
> 雖然華碩的 codebase 不斷進版，但從這陣子的專案維護所得到的經驗是：
> 
> 1. 華碩進版所新增的功能大多都是私有的應用(AiMesh、AiProtection、AiCloud...等)，大多不會公開原始碼而且有些會跟 model 相依。
> 2. 發現華碩後來的 codebase 進版其實也是多著重在 11ac/11ax，幾乎沒有 11n 的功能新增（也就是不少 n18u 其實都用不到），在這樣的 codebase 下反而多少會增加 code size。
> 3. Merlin 所維護的專案排除進版華碩的 codebase 情況下，也多只能從 opensource、或自行實作功能；並且多少也會遇到 binary 不相容的問題。
> 
> 以這個專案而言，基本上保留 n18u 華碩官方原廠軔體既有的功能下，又能整合 merlin 的 opensource 的強化與 bugfix，我個人認為其實已經達到當初創立這個專案的目標了。
> 
> 對 merlin 專案來說，由於他們會持續進版 codebase，所以陸續會有跟不上更新的裝置會被停止支援（如 RT-AC56U），就算 ac68u 也會有被 merlin 停止支援的一天（只要華碩停止頻繁更新 binary）。
> 因為 binary 是個黑合子，我很難去確定華碩在程式的寫法完美相容所有狀況，因此就以確定可完整支援 n18u 的 GPL 為基礎來疊加 merlin 了。
> 
> 不過你所提的方式我覺得是可行的，有興趣的話其實你也可以另創專案去實踐你的想法，我這邊則可以提供之前整合這個專案的一些相關經驗，大家可以互相討論這樣~

我了解了,非常感谢!非常感谢你的工作!如果能找到更多我能做的事,我一定多加支援你,也是为了这个路由器可以更大的发挥其功效.

另外,我认为,如果以后我们跟不上官方梅林的脚本,那么我们紧跟asuswrt的脚本也是好的,因为一切安全补丁是很有用的,而至于梅林的功能,目前大概除了bug fix之外,已经非常足够的给rt-n18u,我能用上这个梅林固件,这里面多亏了你的辛劳:)
