### ISSUE TITLE
remote syslog seems some problem in 384.13b1

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#14]
USB3问题好使了,但是看来这个版本更新具体,目前发现远程日志功能不能正常使用了.

Nov 20 20:41:58 router syslog: cannot connect to 10.0.0.21:514: Connection refused [v8.38.0 try http://www.rsyslog.com/e/2027 ]
Nov 20 20:43:17 router sen: hi
Nov 20 20:43:17 router syslog: cannot connect to 10.0.0.21:514: Connection refused [v8.38.0 try http://www.rsyslog.com/e/2027 ]

在自带的一般记录文件里,似乎过滤日志级别也不管用了,所有的日志通通都会被记载下来.

**Comment by gzenux** [comment]
In this beta release, I change syslog to rsyslog since the new asuswrt has rsyslog support.

The remote log feature in rsyslog uses TCP connection to send the log message. I don't use the remote log feature but I think maybe you could check your remote log server setting to ensure it can accept TCP connection.

What's the value in the nvram 'message_loglevel'?
(run "nvram get message_loglevel" in your rt-n18u device)

**Comment by SLboat** [comment]
收到,我今天再试下,不明白为什么走tcp呢一般的日志服务器首选都是udp吧,因为日志丢了也无所谓,这是梅林的新设定吗?


From SLboat

**Comment by SLboat** [comment]
今天抽空稍微再测试了下,tcp日志很遗憾也没有工作起来.


From SLboat

**Comment by SLboat** [comment]
我的测试不太充足,可能问的有点唐突,我是没有清空nvram来更新的,我去看了提交,你有一个说到了用了新的日志级别,我会再去看看.


From SLboat

**Comment by gzenux** [comment]
There is no special reason to choose TCP connection. It's because of hard-coded rsyslog configuration by AsusWRT.(Not Merlin-specific settings)

I tried the remote log feature (using rsyslog as the remote log server) and it seems to work fine.

**Comment by SLboat** [comment]
感谢回馈,我很需要udp功能,因为日志服务器经常会挂掉,我等后面的beta2等出来再做测试一番.

**Comment by gzenux** [comment]
I add a logging protocol switch option for rsyslog feature. It allows you to choose either TCP or UDP to send the log message.

Please try the following attached patch which is based on tag 'rtn18u_384.13-beta1' to verify it works or not.
[rsyslog_issue.zip](https://github.com/gzenux/asuswrt-rtn18u/files/3890666/rsyslog_issue.zip)

**Comment by SLboat** [comment]
非常感谢!但我这里没有编译环境这会,能否给我个预编译包呢?

我主要使用日志服务器来跟踪entware里工具的信息,还是很好用的,当然如果纯粹的路由器日志,就没有太多这样做的必要了.


From SLboat

**Comment by gzenux** [comment]
I think it's okay to wait for the next beta release since you have no build environment.

**Comment by SLboat** [comment]
没问题的!我慢慢等!


From SLboat

**Comment by SLboat** [comment]
beta2 测试了!可以正常工作日志了!
![image](https://user-images.githubusercontent.com/4231376/70139089-b5f39380-16cc-11ea-8674-af66adc1b871.png)

除了开机的时候有一些错误无用的日志:
![image](https://user-images.githubusercontent.com/4231376/70139140-c73ca000-16cc-11ea-888f-9c2857146735.png)
