### ISSUE TITLE
流量监控似乎没有显示出来流量

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#17]
发现384.13没有即时流量显示,不知道是不是本来这样设计的呢?
流量管理-流量监控

![image](https://user-images.githubusercontent.com/4231376/71254538-40dbbb80-2366-11ea-9d7d-6fc3d8099321.png)

**Comment by SLboat** [comment]
很高兴出正式版了:)
这些功能其实也都不是特别有用...app里还是可以看的

**Comment by gzenux** [comment]
It works fine on my router.

![0](https://user-images.githubusercontent.com/6124290/71257944-f2331f00-236f-11ea-96df-1c052fc05bc1.png)

**Comment by SLboat** [comment]
真奇怪,看来和命令行的问题一样.我是Chrome+Mac catlina的环境.


From SLboat

**Comment by SLboat** [comment]
奇怪,这会儿又可以了,看来是必须点了页面后,等待一会儿...


From SLboat
