### ISSUE TITLE
Missing Firmware Downgrade Link

### ISSUE THREAD

**Issue by Spiek** [gzenux/asuswrt-rtn18u#2]
In your [install documentation ](https://gzenux.github.io/asuswrt-rtn18u/) you mention a downgrade to 382_39935, if the router was allready upgraded to a higher version.

But the download link to this version is not available anymore on the official asus page.

You may could add this link to your Documentation if yout want, so that others don't have to search for it:
https://dlcdnets.asus.com/pub/ASUS/wireless/RT-N18U/FW_RT_N18U_300438239935.ZIP

I wanted to send you a pull request, but your repo is soo big that i get some troubles checking it out 

PS: this is not a "real" issue if you don't want to add the link, just close the issue

Best Regards

**Comment by gzenux** [comment]
I tried to install 384.8_2 from official 382_50624 (current latest version) without any problem.

It seems no need to downgrade anymore and rt-n18u can use either online or manual method to update to 382_50624.

I have updated the 384.8_2 release note.

Thanks for your friendly reminder!
