### ISSUE TITLE
Issue on page QoS_EZQoS.asp Asuswrt-Merlin_RT-N18U_384.13_0

### ISSUE THREAD

**Issue by frlr-GH** [gzenux/asuswrt-rtn18u#20]
Hi team,

Experienced on version 384.12 and 384.13 : the page QoS_EZQoS.asp does not work properly anymore on my ASUS RT-N18U.

As shown on the attached screens, once QOS activated :
* Selection box only show the Choice : 'QOS Configuration' . 2 others choices 'user-defined QoS rules' and 'user-defined QoS rules' are not available anymore.
* Bandwidth values are not displayed in the fields when page is reloaded

Same Box works Properly on following pages 
* <IP>/Advanced_QOSUserRules_Content.asp
* <IP>/Advanced_QOSUserPrio_Content.asp

Page in version 384.11_2 is OK 

Thanks for your great work.

![image](https://user-images.githubusercontent.com/59410955/71641167-8c139980-2c97-11ea-867d-5172c0a175f5.png)

![image](https://user-images.githubusercontent.com/59410955/71641188-a3528700-2c97-11ea-8297-a0a4c3eac303.png)

![image](https://user-images.githubusercontent.com/59410955/71641193-afd6df80-2c97-11ea-871b-a0f88359b3c0.png)

**Comment by gzenux** [comment]
I find the root cause and will fix it on the next release.

**Comment by gzenux** [comment]
The rtn18u_384.13_1 release is now available.
Use this firmware for this issue.
