### ISSUE TITLE
Low speed through ethernet

### ISSUE THREAD

**Issue by dornt2** [gzenux/asuswrt-rtn18u#22]
I flashed Asuswrt-Merlin for RT-N18U firmware on my router, over latest original firmware "RT-N18U_3.0.0.4_382_51640-g679a7e3" and seems to be some problems. 
These are my unsofisticated tests (1Gbps subscription, tests on fast.com on browsers):

- with original firmware "RT-N18U_3.0.0.4_382_51640-g679a7e3.trx"
wireless on my phone ~ 53 Mbps
wireless on desktop ~ 210 Mbps
ethernet ~ 1.1Gbps​
- with Asuswrt-Merlin for RT-N18U "RT-N18U_384.13_1.trx"
wireless on my phone ~ 53 Mbps
wireless on desktop ~ 210 Mbps
ethernet ~ 330 Mbps !!!!​

Something wrong (very) on the usage through the cable and nothing improved on the wireless (with my devices and my configuration of course).

I restored the latest manufacturer firmware and the speed through wire comes back.

**Comment by Eldenroot** [comment]
Is CTF enabled? Please check and let us know

**Comment by dornt2** [comment]
I had enabled "Jumbo Frame" in "Switch Control" and "NAT Acceleration" was on "Auto"; I didn't change anything here.
... and, of course I set up everything manually, not from a backup file.

Now, the speed through ethernet is ~ 1.4 
![RT-N18U_Merlin_eth_connection](https://user-images.githubusercontent.com/42633858/72216828-e2ea6000-352e-11ea-9979-8d35c8ef9c6a.png)
Gbps.

Everything is fine now.
