### ISSUE TITLE
poor wifi perfomance 

### ISSUE THREAD

**Issue by elfnino** [gzenux/asuswrt-rtn18u#23]
First let me thank you for bringing Merlin to RTN18U !
I am experiencing very poor wifi performance  with 384.13_1 release.
Bitrates are 10 times slower and latency is huge  60-260ms  on multiple types of laptops with  W10 but also  iphone and  ipad
I have cleared NVram to factory settings and reconfigured just basics Wifi security and ISP PPP login credentials  and CPU usage is low.  
Wired LAN perfomrmance is good as on stock FW

**Comment by gzenux** [comment]
The WiFi performance will vary based on many factors.
I ping the router from my the laptop (via wireless) for the latency test and most responses are 1-3ms, it seems to be no problem.
What's your device topology on the router? It might need a further description of your testing to clarify the issue.

**Comment by elfnino** [comment]
I cannot understand what fixed the issue but after second re-flash from stock to Merlin the WiFi performance is fine. Only difference I did was extra factory reset on stock FW  before flashing with Merlin.  Initially I did factory reset only on Merlin.  
Doesn't make much sense but I'm happy it works now. Thank you for your support.
