### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Eldenroot** [gzenux/asuswrt-rtn18u#26]
@gzenux 

I wanna thank you for your time and effort to bring Asus-wrt to Asus RT-N18u :)

I hope you will support this router for a long time, because it is a really good product!

Take care, keep good work!

**Comment by Eldenroot** [comment]
@gzenux - is RT-N18u still supported by Asus? Because latest official firmware is almost 1 year old. Do you have any news?

**Comment by gzenux** [comment]
No, I don't know Asus's support plan for RT-N18U.
I'll still merge Asuswrt-Merlin update for RT-N18U in my free time but there is no guarantee of the stability on every merge.
A bug fix pull request is also welcome to make this project better.

**Comment by Eldenroot** [comment]
Please continue in your great effort!
