### ISSUE TITLE
[Question] Which version of Samba is supported?

### ISSUE THREAD

**Issue by ashishpatel1992** [gzenux/asuswrt-rtn18u#34]
I would like to know which version of samba is used by this build. As I want to share my hard drive over the network so that it can be accessible over Windows/macOS/Ubuntu

The original firmware from Asus only supports SMBv1, which is not supported by all the OS

**Comment by gzenux** [comment]
SMBv1 and SMBv2 are available by this build.
You could choose the protocol version which you prefer from the WebGUI.
