### ISSUE TITLE
[Question] What is default ID and password?

### ISSUE THREAD

**Issue by ashishpatel1992** [gzenux/asuswrt-rtn18u#35]
What is the default ID and password?
I have tried my own id and password setup from original firmware but that doesn't work.
Also tried username: `admin` and  password: `admin`
Both of them not working.
Any ideas of how can I get into the router?

**Comment by gzenux** [comment]
Please refer to the "Installation" section in this project website if your router is coming from the official AsusWRT.

**Comment by ashishpatel1992** [comment]
Finally nothing worked had to hard reset the router.
