### ISSUE TITLE
Update dnsmasq to 2.84

### ISSUE THREAD

**Issue by curiosoplus** [gzenux/asuswrt-rtn18u#41]
Hi! Before all... Thank you for this excellent work! 
This last firmware includes dnsmasq **2.82**, has you know a vulnerability called "dnspooq" is spreading,  i know that was fixed with version **2.83** or earlier... 
Could you update latest firmware with dnsmasq **2.84**?

Best regards!

**Comment by gzenux** [comment]
I have updated dnsmasq to 2.84.
Please use rtn18u_384.19_1 release instead.

**Comment by curiosoplus** [comment]
Thanks!
