### ISSUE TITLE
Bug in Version 386.1_1 WiFi Connection Problem

### ISSUE THREAD

**Issue by manirhossen** [gzenux/asuswrt-rtn18u#43]
After Upgrading this 386.1_1 version I'm unable to connect with WiFi. Everytime it shows wrong password. I'm unable to connect with wifi router with Authentication Method: WPA2-Personal. But I'm able to connect with Open System.

**Comment by strassada** [comment]
I confirm this bug.
in AP mode
![Image_00033](https://user-images.githubusercontent.com/46635081/109353731-1005e900-787d-11eb-9208-57cf43bf5bcf.png)
![Image_00036](https://user-images.githubusercontent.com/46635081/109353966-62dfa080-787d-11eb-87c1-0aec3dfeeff9.png)
Netqwork map does not report wireless client

**Comment by walk1ndude** [comment]
Same problem. Reverted to 384.19_1 (386.1_0 didn't help - still no wpa2)

**Comment by jakubtrhon** [comment]
Same here, reverted back to 384.19_1

**Comment by Zed-technics** [comment]
Same here, reverted back to 384.19_1

**Comment by h0353914** [comment]
Same here, reverted back to 384.19_1

**Comment by gzenux** [comment]
Release 386.1_2 now is available and it should fix this problem.

**Comment by pedro16v** [comment]
> Release 386.1_2 now is available and it should fix this problem.

I have just upgraded and I'm back to normal. Thanks!
