### ISSUE TITLE
CPU spikes on 386.1_2

### ISSUE THREAD

**Issue by jakubtrhon** [gzenux/asuswrt-rtn18u#44]
Found another issue in 386.1_2 firmware - cpu spikes in every few seconds
![image](https://user-images.githubusercontent.com/59135234/109551576-04126500-7ad1-11eb-9938-d2d1c879f30d.png)

from top it looks like mtdblock3 process is spiking

when reverted back 384.19_1 it's okay

**Comment by jakubtrhon** [comment]
after factory reset it's okay, probably only my configuration issue

**Comment by manirhossen** [comment]
same problem in my router. After Factory Reset Same problem happend in my Router.
