### ISSUE TITLE
Site Survey not working

### ISSUE THREAD

**Issue by manirhossen** [gzenux/asuswrt-rtn18u#49]
In My latest **Firmware Version: 386.2** my **Site Survey** not working. Please some one test it and reply me. 

![image](https://user-images.githubusercontent.com/56219261/115723137-7b61c800-a3a1-11eb-9294-00124abb0efa.png)

**Comment by gzenux** [comment]
I have no such problem in the site survey page.

**Comment by manirhossen** [comment]
> I have no such problem in the site survey page.

Did you find any WIFI signal in your router **Site Survey** .?

**Comment by gzenux** [comment]
> > I have no such problem in the site survey page.
> 
> Did you find any WIFI signal in your router **Site Survey** .?

Yes, my site survey result shown as the following:

![site_survey](https://user-images.githubusercontent.com/6124290/115798071-f3fb6f80-a407-11eb-8a02-4a02e94c2b62.png)

**Comment by manirhossen** [comment]
> > > I have no such problem in the site survey page.
> > 
> > 
> > Did you find any WIFI signal in your router **Site Survey** .?
> 
> Yes, my site survey result shown as the following:
> 
> ![site_survey](https://user-images.githubusercontent.com/6124290/115798071-f3fb6f80-a407-11eb-8a02-4a02e94c2b62.png)

**I just found one Bug in this latest firmware.**
Now My Router working prefect.  First I install DD-WRT in my router & than reset my router. After reset I install Asuswrt latest firmware and after install it. I reset my router again. Now my Router is working Perfectly. 

**But Now I notice one problem in this firmware.** 

![bug](https://user-images.githubusercontent.com/56219261/115887358-aa486e80-a473-11eb-972c-c58cf79af0bb.png)

**Bug: When I Turn On **Wireless MAC Filter** than **Site Survey** not working. When I Turn Off Wireless MAC Filter than **Site Survey** working perfectly.** 

**Please @gzenux Reply me is this is a Bug.**

**Comment by gzenux** [comment]
> **Bug: When I Turn On **Wireless MAC Filter** than **Site Survey** not working. When I Turn Off Wireless MAC Filter than **Site Survey** working perfectly.**
> 
> **Please @gzenux Reply me is this is a Bug.**

I don't know. I think this should not be a bug in my opinion since the wireless MAC filter feature is enabled.

I can see no any sites (this is the same result as your description) when "MAC Filter Mode" is set to "Accept" with input MACs which are not in the survey sites.

When the input MACs are in the survey sites, the site survey page shows only these sites (Also in the "Accept" mode).
