### ISSUE TITLE
能否集成koolshare的软件中心，谢谢。

### ISSUE THREAD

**Issue by zzzshanghai** [gzenux/asuswrt-rtn18u#5]
您好，这个项目在HGG停止更新后，为我们的N18U赋予了新的生命力。感谢感谢。

建议是否可以集成koolshare论坛的软件中心，让N18U也可以直接使用插件。谢谢。

**Comment by gzenux** [comment]
此專案目前只會整合官方梅林功能（在我個人能力所及的情況下），若梅林官方本身有納入 koolshare 軟體中心功能才會考慮進一步整合。

另外，也歡迎其他愛好 N18U 的開發者 fork 此 opensource 專案來進一步支援 koolshare 軟體中心以造福相關的使用者！

**Comment by SLboat** [comment]
哈!原来移植者懂中文,真是太好了!
