### ISSUE TITLE
Asus RT-N18U as repeater - small issue with dnsmasq

### ISSUE THREAD

**Issue by shaarkys** [gzenux/asuswrt-rtn18u#54]
Hi, @gzenux 

I'm using two Asus RT-N18U with 386.3 and the 2nd one in mode of repeater is repeatedly restarting dnsmasq - can someone advise how to fix that ?

Thank you for reply and thank you for your fork !

> Sep 15 20:43:10 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:43:43 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:44:13 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:44:46 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:45:16 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:45:48 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:46:18 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:46:50 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:47:20 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:47:53 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:48:23 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:48:55 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:49:25 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:49:57 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:50:27 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:50:59 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:51:29 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:52:02 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:52:32 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:53:04 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:53:34 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:54:07 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:54:37 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:55:09 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:55:39 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:56:12 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:56:42 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:57:15 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:57:45 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:58:17 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:58:47 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:59:19 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 20:59:49 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 21:00:22 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 21:00:52 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 21:01:24 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq
Sep 15 21:01:54 RT-N18U-A584back rc_service: watchdog 180:notify_rc start_dnsmasq

**Comment by gzenux** [comment]
> I'm using two Asus RT-N18U with 386.3 and the 2nd one in mode of repeater is repeatedly restarting dnsmasq - can someone advise how to fix that ?
> 
This issue is caused by upstream 386.1merged code.
Please use release 384.19_1 or older one.

**Comment by shaarkys** [comment]
Seems that error is gone after downgrading to 384.19_1 - I didn't have to perform reset. Thank you.
